# Solution for assignment on Lecture 14

https://course.masaischool.com/assignments/12447/

#### Required CSV files are available in my DRIVE. While providing path, you have to provide path in your Google Drive or local machine

In [ ]:
import csv

# Q1. Births_USA

In [ ]:
path = "/content/drive/MyDrive/Colab Notebooks/births_usa.csv"

with open(path, 'r') as f:
  reader = csv.reader(f)
  # read column names
  cols = next(iter(reader))
  # read rows
  rows = []
  for i in reader:
    rows.append(i)

In [ ]:
print(cols)

['month', 'total_births']

In [ ]:
len(rows)

5479

In [ ]:
# sample 1 row
rows[0]

['2000', '1', '1', '6', '9083']

In [ ]:
# we are interested in month, which is available as numbers as well as births
# create a list of months

months_list = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]

# create a dictionary of months as keys and births as values
d = dict.fromkeys(months_list, 0)
d

{'April': 0,
 'August': 0,
 'December': 0,
 'February': 0,
 'January': 0,
 'July': 0,
 'June': 0,
 'March': 0,
 'May': 0,
 'November': 0,
 'October': 0,
 'September': 0}

In [ ]:
# iterate through all the rows in CSV file and manipulate

for row in rows:
  month_idx = int(row[1])
  birth_count = int(row[-1])

  # update in dictionary
  # month starts with 1 and ends with 12
  # but index starts with 0 and ends with 11
  month_name = months_list[month_idx-1]
  d[month_name] =d[month_name]+ birth_count

IndexError: ignored

In [ ]:
# print report
for k,v in d.items():
  print(k,v,sep='-')


# for month in months_list:
#   print(month, d[month], sep=" - ")

January-5072588
February-4725693
March-5172961
April-4960750
May-5195445
June-5163360
July-5450418
August-5540170
September-5399592
October-5302865
November-5008750
December-5194432

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# write report in a CSV file
write_path = "/content/drive/MyDrive/Colab Notebooks/births_usa.csv"

with open(write_path,'w') as f:
  writer = csv.writer(f)
  # write column names
  writer.writerow(['month', 'total_births'])
  # write data
  for month in months_list:
    writer.writerow([month, d[month]])

In [ ]:
with open("/content/drive/MyDrive/Colab Notebooks/births_usa.csv",'r') as f:
  reader=csv.reader(f)
  for i in reader:
    print(i)

['month', 'total_births']
['January', '5072588']
['February', '4725693']
['March', '5172961']
['April', '4960750']
['May', '5195445']
['June', '5163360']
['July', '5450418']
['August', '5540170']
['September', '5399592']
['October', '5302865']
['November', '5008750']
['December', '5194432']

# Q2 Births_USA_2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# we are interested in weekday, which is available as numbers, as well as births
# create a list of weekdays

week_list = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]

# create a dictionary of weeks as keys and births as values
d1 = dict.fromkeys(week_list, 0)
d1

{'Friday': 0,
 'Monday': 0,
 'Saturday': 0,
 'Sunday': 0,
 'Thursday': 0,
 'Tuesday': 0,
 'Wednesday': 0}

In [ ]:
s=set()
for row in rows:
  s.add(row[-2])

s

{'1', '2', '3', '4', '5', '6', '7'}

In [ ]:
# iterate through all the rows in CSV file and manipulate

for row in rows:
  week_idx = int(row[-2])
  birth_count = int(row[-1])

  # update in dictionary
  # week starts with 1 and ends with 7
  # but index starts with 0 and ends with 6
  week_name = week_list[week_idx-1]
  d1[week_name] += birth_count

NameError: ignored

In [ ]:
# print report 
print(*week_list, sep=",")
print(*[d1[week] for week in week_list], sep=",")
# for k,v in d1.items():
#   print(k,sep=",")
# print()
# for k,v in d1.items():
#    print(v,sep=",")

Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday
9316001,10274874,10109130,10045436,9850199,6704495,5886889

In [ ]:
# write in a CSV file

write_path = "/content/drive/MyDrive/PT_DA_13/CSV_Assignment/births_usa_2_report.csv"

with open(write_path,'w') as f:
  writer = csv.writer(f)
  # write column names
  writer.writerow(week_list)
  # write data
  writer.writerow([d1[week] for week in week_list])

# Q3 Temperatures

In [ ]:
path = "/content/drive/MyDrive/PT_DA_13/CSV_Assignment/temperatures.csv"

with open(path, 'r') as f:
  reader = csv.reader(f)
  cols = next(iter(reader))
  rows = []

  for i in reader:
    rows.append(i)

  print(len(rows), len(cols))

365 13

In [ ]:
# what columns are there?
cols

['date',
 'actual_mean_temp',
 'actual_min_temp',
 'actual_max_temp',
 'average_min_temp',
 'average_max_temp',
 'record_min_temp',
 'record_max_temp',
 'record_min_temp_year',
 'record_max_temp_year',
 'actual_precipitation',
 'average_precipitation',
 'record_precipitation']

In [ ]:
# how a row looks like?
rows[0]

['2014-7-1',
 '70',
 '63',
 '77',
 '63',
 '82',
 '52',
 '107',
 '1886',
 '1985',
 '0',
 '0',
 '0.09']

In [ ]:
# we are interested in month, year, actual_min_temp, actual_max_temp
summary = {}

for row in rows:
  date = row[0]
  year,month,day = map(int,date.split("-"))

  actual_min_temp = int(row[2])
  actual_max_temp = int(row[3])

  # add necessary data
  # if year, month pair is new, create a key-value pair
  if (year, month) not in summary:
    summary[(year, month)] = [actual_min_temp, actual_max_temp]    

  else:
    # compare and update
    if actual_min_temp < summary[(year, month)][0]:
      summary[(year, month)][0] = actual_min_temp 

    if actual_max_temp > summary[(year, month)][1]:
      summary[(year, month)][1] = actual_max_temp
    
len(summary)

12

In [ ]:
# write in a CSV file
write_path = "/content/drive/MyDrive/PT_DA_13/CSV_Assignment/temperatures_summary.csv"
with open(write_path, 'w') as f:
  writer = csv.writer(f)

  # write column headers
  new_cols = ["year", "month", "actual_min_temp", "actual_max_temp"]
  writer.writerow(new_cols)
  print(new_cols)
  # write data
  for key,val in sorted(summary.items()): 
    data = [key[0], key[1], val[0], val[1]]
    writer.writerow(data)
    print(data)

['year', 'month', 'actual_min_temp', 'actual_max_temp']
[2014, 7, 62, 92]
[2014, 8, 63, 91]
[2014, 9, 61, 103]
[2014, 10, 59, 98]
[2014, 11, 51, 90]
[2014, 12, 39, 83]
[2015, 1, 37, 85]
[2015, 2, 46, 88]
[2015, 3, 48, 93]
[2015, 4, 49, 92]
[2015, 5, 50, 84]
[2015, 6, 58, 91]

In [ ]:
import numpy as np

In [ ]:
n=np.zeros(2)
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.

    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.

    Examples
    --------
    >>> np.zeros(5)
    array([ 0.,  0.,  0.,  0.,  0.])

    >>> np.zeros((5,), dtype=int)
    array([0, 0, 0, 0, 0])

    >>> np.zeros((2, 1))
    array([[ 0.],
           [ 0.]])

    >>> s = (2,2)
    >>> np.zeros(s)
    array([[ 0.,  0.],
           [ 0.,  0.]])

    >>> np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype
    array([(0, 0), (0, 0)],
          dtype=[('x', '<i4'), ('y', '<i4')])

In [ ]:
import csv
with open("/content/drive/MyDrive/Colab Notebooks/births_usa.csv",'r') as f:
  reader=csv.reader(f)
  # Header column is seperated out from other rows
  cols=next(iter(reader))
  print(cols)

['month', 'total_births']